import {Colors, FontSize} from '@utils';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: Colors.Background,
    paddingHorizontal: 15,
    paddingBottom: 0,
  },
  secondView: {
    backgroundColor: Colors.White,
    paddingHorizontal: 10,
    paddingBottom: 30,
    bottom: -15,
  },
  title: {
    fontSize: FontSize.H3,
    fontWeight: 'bold',
    color: Colors.Black100,
    textAlign: 'center',
    marginHorizontal: 20,
    marginTop: 20,
  },
  description: {
    fontSize: FontSize.H6,
    fontWeight: '500',
    color: Colors.GrayText,
    textAlign: 'center',
    marginHorizontal: 50,
    marginTop: 10,
  },
  buttonShadowView: {
    shadowColor: Colors.Primary,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
    flex: 1,
    backgroundColor: Colors.White,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    padding: 15,
  },
  offerDetailTitle: {
    fontSize: FontSize.BodyBig,
    fontWeight: '500',
    color: Colors.Black100,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  label: {
    fontSize: FontSize.BodyBig,
    fontWeight: '500',
    color: Colors.GrayText,
    marginTop: 15,
  },
  value: {
    fontSize: FontSize.H5,
    fontWeight: '400',
    color: Colors.Black100,
    marginTop: 3,
  },
  bottomSheetView: {
    paddingVertical: 10,
    paddingHorizontal: 30,
    position: 'absolute',
    bottom: 0,
    backgroundColor: Colors.White,
    width: '100%',
    shadowColor: Colors.Primary,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
    alignItems: 'center',
  },
  termsAndConditions: {
    fontSize: FontSize.BodyBig,
    fontWeight: '400',
    color: Colors.Black100,
    textAlign: 'center',
  },
  termsAndConditionsBlue: {
    fontSize: FontSize.BodyBig,
    fontWeight: '600',
    color: Colors.Blue,
  },
  collectButton: {
    marginTop: 15,
    width: '75%',
  },
  CollectHeadercontainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.White,
    borderBottomWidth: 1,
    borderBottomColor: Colors.Border,
    padding: 10,
  },
  leftContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    height: '100%',
  },
  imageView: {
    flexDirection: 'row',
  },
  roundImage: {
    width: 25,
    height: 25,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: Colors.White,
  },
  imageOverlap: {
    position: 'absolute',
    right: -15,
  },
  imageOverlap1: {
    position: 'absolute',
    right: -30,
  },
  centerContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    flex: 1,
    height: '100%',
  },
  name: {
    fontSize: FontSize.H6,
    color: Colors.Black100,
    fontWeight: 'bold',
  },
  headerLabel: {
    fontSize: FontSize.BodyBig,
    color: Colors.Shadow,
    fontWeight: '500',
  },
  rightContainer: {
    flex: 1,
    alignItems: 'center',
    flexDirection: 'row',
    height: '100%',
    gap: 5,
    justifyContent: 'flex-end',
  },
});
